apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nginx-image-meta
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/rodriguesalex/nginx-image-meta.git
  ref:
    branch: main
  secretRef:
    name: nginx-image-meta-ssh