apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-image-meta
  namespace: flux-system
spec:
  interval: 1m
  path: ./
  prune: false
  sourceRef:
    kind: GitRepository
    name: nginx-image-meta
  targetNamespace: default
  dependsOn:
    - name: nginx-app