apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - gitrepository-nginx-image-meta.yaml
  - kustomization-nginx-image-meta.yaml
  - ../apps/nginx-image-meta

patchesStrategicMerge:
  - patch-replicas.yaml